# Generated by Django 3.2.14 on 2023-02-24 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=255)),
                ('questions', models.CharField(blank=True, max_length=1000, null=True)),
                ('answers', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.seedfarm')),
            ],
        ),
    ]
