# Generated by Django 3.2.14 on 2023-02-27 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('Product_Category', models.CharField(choices=[('Fertilizer', 'Fertilizers'), ('Seeds', 'Seeds'), ('Accessories', 'Accessories')], max_length=255)),
                ('Product_price', models.IntegerField()),
                ('Product_image', models.FileField(upload_to='farmer_product')),
                ('Product_stock', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
