# Generated by Django 3.2.14 on 2023-02-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productforcustomer',
            old_name='ProductName',
            new_name='Product_Name',
        ),
        migrations.AlterField(
            model_name='productforcustomer',
            name='Product_Category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegitable', 'Vegitable'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productforcustomer',
            name='Product_Stock',
            field=models.IntegerField(),
        ),
    ]
