# Generated by Django 3.2.14 on 2023-02-28 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_auto_20230228_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforcustomer',
            name='Product_Category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('other', 'other')], max_length=255),
        ),
        migrations.CreateModel(
            name='CustomerCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('Payment', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productforcustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
